name: Deploy to Cloud Runtime

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cloud Runtime CLI
        uses: Vonage/cloud-runtime-cli@main
      - name: Deploy
        run: |
          vcr deploy \
            --api-key ${{ secrets.VONAGE_API_KEY }} \
            --api-secret ${{ secrets.VONAGE_API_SECRET }} \
            --region aws.use1
